version: '3.8'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: your_user
      POSTGRES_PASSWORD: your_password
      POSTGRES_DB: your_database
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  streamlit:
    build: ./streamlit_app
    ports:
      - "8501:8501"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://your_user:your_password@db:5432/your_database

volumes:
  pg_data:
